apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        # CHANGE 'YOUR_DOCKER_USERNAME' TO YOUR ACTUAL DOCKER HUB USERNAME
        image: rajeevgangaraju/poc20:b8b65eaa9a07222b7395b3f8d6ac9bd16b382c85
        ports:
        - containerPort: 5000
