apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app
        # CHANGE 'YOUR_DOCKER_USERNAME' TO YOUR ACTUAL DOCKER HUB USERNAME
        image: rajeevgangaraju/poc20:2b6f41e573d0818070298f647262246fe765ada9
        ports:
        - containerPort: 5000
